name: dox
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  http: ^0.13.3
  get_it: ^7.1.3
  bubble: ^1.2.1
  image_picker: ^0.8.0+1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.6
  firebase_auth: ^3.3.11
  firebase_core: ^1.2.1
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  google_sign_in: ^5.0.4
  font_awesome_flutter: ^9.2.0
  shimmer: ^2.0.0
  carousel_pro: ^1.0.0
  firebase_messaging: ^11.2.11
  like_button: ^2.0.2
  flutter_launcher_icons: ^0.9.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
assets:
    - images/

  # fonts:

  #   - family: Poppins-Bold
  #     fonts:
  #       - asset: assets/fonts/Poppins-Bold.ttf

  #   - family: Poppins-Medium
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
  
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/RobotoCondensed-Regular.ttf
